import {
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
  IMPRIMANTE_COULEUR_LASER_SPC840,
  IMPRIMANTE_RICOH_P501,
  IMPRIMANTE_RICOH_SP3710DN,
  IMPRIMANTE_RICOH_SP4510DN,
  IMPRIMANTE_RICOH_SP4520DN,
  BM5100,
  BP5100DN,
  P3300DN,
  P3300DW,
  P25009W,
  P25009,
  CP2200DW,
  M6559N,
  M6609N,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "imprimante",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  // =================== bac de dechet =================

  {
    _id: "217",
    img: bac1,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },

  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },

  // =================== encre =================

  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Encre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Encre",
  },

  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Encre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Green",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Encre",
  },

  // =================== ruban =================

  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },

  // =================== imprimante hp =================

  {
    _id: "hp1",
    img: hp1,
    productName:
      "IMPRIMANTE HP JET D'ENCRE HP SMART TANK 516 COULEUR MFP 3EN1 A4 WIFI",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "Desc : Imprimante Jet D'encre HP SMART TANK 516 3en1 Couleur 3YW70A - Fonction: Impression, Copie, Numérisation - Technologie d'impression: jet d'encre - Vitesse d'impression Noir : Jusqu'à 22 ppm - Vitesse d’impression Couleur : Jusqu'à 16 ppm - Résolution d'impression Couleur : 1200x1200dpi - Format Papier : A4 - Capacité Papier : 100 feuilles -  Cycle d'utilisation (mensuel, A4) : Jusqu'à 1000pages - Connectivité: USB 2.0 haute vitesse, Wi-Fi, Bluetooth LE -  Dimensions: 447 x 373 x 158 mm - Garantie: 1 an",
    cat: "Imprimante",
    pdf: "",
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "3YW70A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Ecran", value: "LCD" },
      {
        label: "Taille de L écran cm",
        value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Technologie d impression", value: "Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Impression", value: "Couleur" },
      { label: "formats", value: "A4" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
      { label: "FAX", value: "Non" },
      { label: "Mémoire", value: "256 Mo" },
      {
        label: "Qualité d impression Noir",
        value: "Jusqu'à 1 200 x 1 200 ppp",
      },
      {
        label: "Qualité d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 ppp",
      },
      { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Connectivite", value: "USB 2.0, WiFi" },
      { label: "Capacité papier", value: "100 feuilles" },
      { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
      {
        label: "Consommation électrique",
        value:
          "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
      },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
      },
      { label: "Poids", value: "5,14 kg" },
      { label: "Dimensions", value: "447 x 373 x 158 mm" },
      { label: "Couleur", value: "Noir et Bleu" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "hp2",
    img: hp2,
    productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "Desc : Imprimante Multifonction Jet d'encre 3 en 1 à réservoir intégré - Impression, numérisation, copie, sans fil - Résolution d'impression: Jusqu'à 4800 x 1200 dpi - Vitesse d'impression Couleur Jusqu'à 15 ppm -Vitesse d'impression N et B Jusqu'à 18 ppm - Résolution du scanner: 1200 x 1200 dpi - Format A4 - Interface USB - Bac d'alimentation de 60 feuilles - Dimensions: 525 x 310 x 158 mm - Garantie 1 an (+ Extension de Garantie 2 Ans ) + 5 Bouteilles",
    cat: "Imprimante",
    pdf: "",
    ficheTech: [],
  },

  {
    _id: "hp3",
    img: hp3,
    productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cat: "Imprimante",
    pdf: "",
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
  // =================== imprimante ricoh =================
  {
    _id: "ricoh1",
    img: ricoh1,
    productName: "IMPRIMANTE RICOH P501",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Ricoh P 501 - Imprimante - Noir et blanc - Recto-verso - LED - A4 - 1200 x 1200 ppp - jusqu'à 43 ppm - capacité : 600 feuilles - USB 2.0, Gigabit LAN, hôte USB 2.0",
    cat: "Imprimante",
    pdf: IMPRIMANTE_RICOH_P501,
    ficheTech: [
      {
        label: "Description du produit",
        value: "Ricoh P 501 - imprimante - Noir et blanc - LED",
      },
      {
        label: "Type d'imprimante",
        value: "Imprimante de groupe de travail - LED - Noir et blanc",
      },
      { label: "Poids", value: "19.3 kg" },
      { label: "Classe de taille de support", value: "A4" },
      { label: "Taille max. du support", value: "A4 (210 x 297 mm)" },
      {
        label: "Vitesse d'impression",
        value: "Jusqu'à 43 ppm - noir & blanc - A4 (210 x 297 mm)",
      },
      { label: "Résolution maximum (N&B)", value: "1200 x 1200 ppp" },
      { label: "Impression recto-verso automatique", value: "Oui" },
      { label: "Interface", value: "USB 2.0, Gigabit LAN, hôte USB 2.0" },
      { label: "AirPrint activé", value: "Oui" },
      { label: "Processeur", value: "1.3 GHz" },
      { label: "RAM installée (maximum)", value: "2 Go (2 Go)" },
      { label: "Langage(s) d'impression", value: "PCL 5E, PCL 6" },
      {
        label: "Type de supports",
        value:
          "Enveloppes, papier uni, papier recyclé, papier à étiquettes, papier préimprimé, papier à en-tête, papier coloré",
      },
      { label: "Capacité totale", value: "600 feuilles" },
      {
        label: "Gestion des supports",
        value: "Bac d'entrée 500 feuilles, bac de dérivation 100 feuilles",
      },
      { label: "Réseaux", value: "Serveur d'impression" },
      {
        label: "Configuration requise",
        value:
          "SCO OpenServer, UNIX, IBM AIX, SunSoft Solaris, HP-UX, Red Hat Linux, Microsoft Windows Server 2008 R2, Microsoft Windows Server 2008, Microsoft Windows Server 2012, Microsoft Windows Server 2012 R2, Microsoft Windows Server 2016, Apple MacOS X 10.10 ou plus récent, Microsoft Windows 7 / 8.1 / 10",
      },
    ],
  },

  {
    _id: "ricoh2",
    img: ricoh2,
    productName: "IMPRIMANTE RICOH SP3710DN",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Grâce à son faible encombrement, la SP 3710DN s'intègre facilement dans les espaces de travail les plus restreints. Malgré son petit gabarit, cet appareil offre des caractéristiques et des fonctionnalités grandioses, telles que l'impression sécurisée et une vitesse d'impression pouvant atteindre 32 ppm.",
    cat: "Imprimante",
    pdf: IMPRIMANTE_RICOH_SP3710DN,
    ficheTech: [
      { label: "Temps de préchauffage (sec.)", value: "26" },
      { label: "Temps sortie de 1ère page (sec.)", value: "7,5" },
      { label: "Vitesse en continu (ppm)", value: "32" },
      { label: "Mémoire : en standard (Mo)", value: "128" },
      { label: "Poids (kg)", value: "13" },
      { label: "Dimensions (l x P x H) (mm)", value: "370 x 392 x 262" },
      {
        label: "Source d'alimentation électrique",
        value: "220 - 240 V, 50/60 Hz",
      },
      {
        label: "Classification laser",
        value: "Produit laser classe (IEC60825 - 1:2014)",
      },
      {
        label: "Langage d'impression : en standard",
        value: "PCL5e, PCL5e (Mac OS), PCL6 (Windows), PostScript 3",
      },
      { label: "Résolution : max. (dpi)", value: "1 200 x 1 200" },
      {
        label: "Interface : en standard",
        value: "Ethernet 10 base-T/100 base-TX, USB2.0 Type B",
      },
      {
        label: "Interface : en option",
        value: "Wireless LAN (IEEE 802.11 a/b/g/n/ac)",
      },
      {
        label: "Environnements Windows®",
        value: "Windows® 7/8.1/10, Windows® Server 2008/2012/2012R2/2016",
      },
      {
        label: "Environnements Mac OS",
        value: "Macintosh OS X v10.10 ou version ultérieure",
      },
      { label: "Autres environnements", value: "Environnement Linux" },
    ],
  },
  {
    _id: "ricoh3",
    img: ricoh3,
    productName: "IMPRIMANTE RICOH SP4520DN",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: " Ricoh SP 4520DN 1200 x 1200 DPI A4 - Imprimantes Laser (LED, 1200 x 1200 DPI, A4, 600 Feuilles, 40 ppm, Impression Recto-Verso)SP 4520DN Imprimante laser monochrome A4, recto-verso, résolution 1200 x 1200 ppp, vitesse jusquà 40 ppm, écran tactile 4.3, capacité totale 600 feuilles, interfaces USB 2.0, Gigabit LAN, Wifi, dimensions (LxPxH) 37 x 39.2 x 42.7 cm, poids 15.5 kg",
    cat: "Imprimante",
    pdf: IMPRIMANTE_RICOH_SP4520DN,
    ficheTech: [
      { label: "Type de produit", value: "Imprimante laser monochrome" },
      { label: "Date de lancement", value: "22/11/2015" },
      {
        label: "Volume d'impression maximum mensuel (duty cycle)",
        value: "10000 pages / mois",
      },
      { label: "Cartouche de démarrage noir livrée", value: "18000 pages" },
      { label: "Capacité mémoire RAM (Standard)", value: "512 Mo" },
      { label: "Capacité mémoire (Maximum)", value: "1536 Mo" },
      { label: "Disque dur", value: "Option / 320 Go" },
      {
        label: "Affichage",
        value: 'Écran tactile LCD (couleur) / 10,9 cm (4,3")',
      },
      {
        label: "Cycle d'utilisation mensuel conseillé (max.)",
        value: "3000 pages / mois",
      },
      {
        label: "Résolution d'impression monochrome (Maximum)",
        value: "1200 x 1200 ppp",
      },
      { label: "Vitesse d'impression 1ère page monochrome", value: "6 s" },
      { label: "Vitesse d'impression (noir, A4)", value: "40 ppm" },
      { label: "Format de papier", value: "A4" },
      {
        label: "Nombre de bacs papier en entrée (Standard)",
        value: "2 bac(s)",
      },
      { label: "Nombre de bacs papier en entrée (Maximum)", value: "4 bac(s)" },
      { label: "Capacité papier en sortie (Standard)", value: "250 feuilles" },
      { label: "Capacité papier en sortie (Maximum)", value: "250 feuilles" },
      { label: "Sortie papier", value: "250 feuilles face dessous" },
      {
        label: "Grammage du support",
        value: "Bac Multiformat : 52 à 162 g/m², Bac standard : 52 à 162 g/m²",
      },
    ],
  },

  {
    _id: "ricoh4",
    img: ricoh4,
    productName: "IMPRIMANTE RICOH COULEUR LASER SPC840",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Imprimante laser couleur Transformer la production légère en avantage de poids ,Imprime jusqu'à 45 ppm,Résolution maximum de 1200x1200 ppp ,Capacité de papier jusqu'à 4 700 pages,Utilisez l’écran tactile intuitif pour produire des impressions professionnelles à l’interne ",
    cat: "Imprimante",
    pdf: IMPRIMANTE_COULEUR_LASER_SPC840,
    ficheTech: [
      { label: "Temps de préchauffage (sec.)", value: "26" },
      { label: "Temps sortie de 1ère page (sec.)", value: "7,5" },
      { label: "Vitesse en continu (ppm)", value: "32" },
      { label: "Mémoire : en standard (Mo)", value: "128" },
      { label: "Poids (kg)", value: "13" },
      { label: "Dimensions (l x P x H) (mm)", value: "370 x 392 x 262" },
      {
        label: "Source d'alimentation électrique",
        value: "220 - 240 V, 50/60 Hz",
      },
      {
        label: "Classification laser",
        value: "Produit laser classe (IEC60825 - 1:2014)",
      },
      {
        label: "Langage d'impression : en standard",
        value: "PCL5e, PCL5e (Mac OS), PCL6 (Windows), PostScript 3",
      },
      { label: "Résolution : max. (dpi)", value: "1 200 x 1 200" },
      {
        label: "Interface : en standard",
        value: "Ethernet 10 base-T/100 base-TX, USB2.0 Type B",
      },
      {
        label: "Interface : en option",
        value: "Wireless LAN (IEEE 802.11 a/b/g/n/ac)",
      },
      {
        label: "Environnements Windows®",
        value: "Windows® 7/8.1/10, Windows® Server 2008/2012/2012R2/2016",
      },
      {
        label: "Environnements Mac OS",
        value: "Macintosh OS X v10.10 ou version ultérieure",
      },
      { label: "Autres environnements", value: "Environnement Linux" },
    ],
  },
  {
    _id: "ricoh5",
    img: ricoh5,
    productName: "IMPRIMANTE RICOH SP4510DN (407313)",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Imprimante laser Noir et Blanc - Format A4 - Vitesse d'impression: 40 ppm - Préchauffage en 17 sec - Première page imprimée en 5 sec - Ecran LCD 4 lignes - Capacité papier standard 600 feuilles - Résolution d'impression: 1200 x 1200 dpi - Interface: USB 2.0 / Ethernet 10 base-T/100 base-TX - Recto/Verso - Garantie 1 an",
    cat: "Imprimante",
    pdf: IMPRIMANTE_RICOH_SP4510DN,
    ficheTech: [
      { label: "Marque", value: "RICOH" },
      { label: "Nom du produit", value: "RICOH SP 4510DN 407313" },
      { label: "Catégorie", value: "IMPRIMANTE" },
      {
        label: "Type d'imprimante",
        value: "Imprimante de groupe de travail - LED - monochrome",
      },
      { label: "Technologie de connectivité", value: "Filaire" },
      { label: "Interface", value: "USB 2.0, Gigabit LAN, hôte USB 2.0" },
      {
        label: "Vitesse d'impression",
        value: "Jusqu'à 40 ppm - noir & blanc - A4 (210 x 297 mm)",
      },
      {
        label: "Durée de sortie de la première impression, Noir et blanc",
        value: "5 s",
      },
      {
        label: "Langage(s) d'impression",
        value: "PCL 5E, PostScript 3, PCL 6, PDF",
      },
      { label: "Support postscript", value: "Standard" },
      {
        label: "Polices incluses",
        value: "45 x PCL, 136 x PostScript 3, 13 x Intellifonts",
      },
      {
        label: "Fonctionnalités de l'imprimante",
        value: "Impression depuis un appareil mobile",
      },
      { label: "Périphériques intégrés", value: "Ecran LCD" },
      { label: "Impression recto-verso automatique", value: "Oui" },
      { label: "Résolution maximum (N&B)", value: "1200 x 1200 ppp" },
      { label: "Capacité totale", value: "600 feuilles" },
      { label: "Capacité des bacs de sortie", value: "250 feuilles" },
      { label: "Formats standard reconnus", value: "A4, A5, B5, A6, B6" },
      { label: "Classe de taille de support", value: "A4" },
      { label: "Grammage", value: "52 g/m² - 162 g/m²" },
      {
        label: "Entrées de média",
        value: "1 x automatique - A4 poids : 52 g/m² - 162 g/m²",
      },
      { label: "Taille max. du support", value: "A4 (210 x 297 mm)" },
      {
        label: "Type de supports",
        value:
          "Papier uni, papier recyclé, papier épais, papier fin, papier préimprimé",
      },
      { label: "Capacité max. du support", value: "1600 feuilles" },
    ],
  },

  // =================== imprimante epson =================

  {
    _id: "espson1",
    img: espson1,
    productName: "IMPRIMANTE EPSON L3251 3EN1 A4 WIFI",
    color: "Blanc",
    badge: true,
    brand: "Epson",
    des: "Imprimante à Réservoir Intégré EPSON ECOTANK L3251 3En1 Couleur Wifi - Fonction: Impression, Copie, Numérisation - Technologie d'impression: Jet d'encre (tête d'impression Epson Micro Piezo) - Vitesse d'impression (N&B/Couleur): 33 pages/min , 15 pages/min - Qualité d'impression noir: 5.760 x 1.440 DPI (ppp) - Qualité d'impression couleur: 5.760 x 1.440 DPI (ppp) - Vitesse de Numérisation: 11 s noir (200 DPI) / 28 s couleur (200 DPI) - Impression recto/verso: Manuel - Format Papier: A4 - Interface: USB, Wi-Fi, Wi-Fi Direct - Capacité Papier: 100 feuilles - Dimensions: 375‎ x 347 x 179 mm - Poids: 3.9 kg - Garantie: 1 an    ",
    cat: "Imprimante",
    pdf: "",
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "Model", value: "BU-C11CJ67409" },
      { label: "Marque", value: "EPSON" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d'impression", value: "Jet d'encre" },
      { label: "Fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Non" },
      {
        label: "Vitesse d'impression Noir",
        value: "33 pages/min Monochrome (papier ordinaire)",
      },
      {
        label: "Vitesse d'impression Couleur",
        value: "15 pages/min Couleur (papier ordinaire)",
      },
      {
        label: "Vitesse d'impression photo",
        value:
          "27 Secondes par photo de 10 x 15 cm (Papier Photo Epson Premium Glacé)",
      },
      { label: "Résolution d'impression", value: "5.760 x 1.440 DPI (ppp)" },
      {
        label: "Type de Scanner",
        value: "Scanner de photos et de documents à plat CIS",
      },
      {
        label: "Vitesse de numérisation",
        value:
          "Recto (A4 en noir) 200 DPI (ppp) - Recto (A4 en couleur) 200 DPI (ppp)",
      },
      {
        label: "Résolution de Numérisation",
        value: "1.200 DPI (ppp) x 2.400 DPI (ppp)",
      },
      { label: "Numérisation en couleur", value: "Oui" },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivité", value: "WiFi" },
      { label: "Formats", value: "A4" },
      { label: "Capacité papier", value: "100 Feuilles" },
      {
        label: "Type de Papier pris en charge",
        value:
          "A4, A6, A5, B5, 10 x 15 cm, 13 x 18 cm, 16:9, DL (enveloppe), N° 10 (enveloppe), C6 (Enveloppe), Letter, Défini par l’utilisateur, Legal",
      },
      {
        label: "Consommation électrique",
        value:
          "12 W (copie autonome, norme ISO/IEC 24712), 0,7 W (mode veille), 4,5 W Prêt, 0,2 W (éteindre), TEC 0,15 kWh/week",
      },
      {
        label: "Cycle d'utilisation Mensuel",
        value: "70 pages /40 impressions photo",
      },
      {
        label: "Alimentation papier standard",
        value: "100 Feuilles Standard - 20 Feuilles photo",
      },
      { label: "Grammage", value: "64 g/m² - 300 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "Quatre bouteilles d’encre individuelles de 65 ml (N,C,J,M) + 1 bouteille d’encre noire supplémentaire, Pilote et programmes d’aide (CD), Appareil principal, Câble électrique, Instructions de montage, Document de garantie",
      },
      { label: "Poids", value: "3,9 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "375‎ x 347 x 179 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "espson2",
    img: espson2,
    productName: "IMPRIMANTE EPSON JET D'ENCRE L3156 COULEUR A4  WIFI",
    color: "Blanc",
    badge: true,
    brand: "Epson",
    des: "Imprimante Jet d'encre L3156 Multifonction 3en1 Couleur - Fonctions: Impression, Copie, numérisation - Format: A4 - Technologie d'impression: Jet d'encre - Vitesse d'impession: 33 ppm (N&B) - Résolution d'impression: 5760 x 1440 DPI - Vitesse de Numérisation: 11s noir (200 DPI), 28 s couleur (200 DPI) - Capacité d'entrée: 100 Feuilles - Fonctionne avec 4 Cartouches (noire, cyan, magenta, jaune) - Dimensions: 375 x 347 x 179 mm - Connectivité: USB, WiFi - Wi-Fi Direct - Poids: 3,9 kg - Garantie: 1 an ",
    cat: "Imprimante",
    pdf: "",
    ficheTech: [
      { label: "Type", value: "Couleur" },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Garantie", value: "1 An" },
      { label: "Formats", value: "A4" },
      { label: "Impression Recto-Verso Automatique", value: "Non" },
      { label: "Fonctions", value: "Multifonction" },
      { label: "Connectivité", value: "Wifi" },
    ],
  },

  // =================== imprimante pantum =================

  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Imprimante PANTUM CP2200DW",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM Couleur - Fonctions: Impression  - Technologie d'impression: Laser - Format Papier: A4 - Vitesse d’impression(Couleur/N&B): 24 ppm (A4) / 26 ppm (Lettre) - Résolution d'impression: 600 x 600 dpi - Sortie papier: 100 page - Mémoire: Double cœur, 1 GHz - Impression recto verso: Automatique - Heure de la première impression: Moins de 11s  - Connecteurs: USB 2.0 haut débit Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Sans fil - Dimensions: 411.2 x 394.1 x 243.7mm - Poids: 16,1 kg - Couleur: Blanc",
    cat: "Imprimante",
    pdf: CP2200DW,
    ficheTech: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "IMPRIMANTE PANTUM BM5100FDW",
    color: "Blanc",
    badge: false,
    brand: "Pantum",
    des: "Pantum BM5100fdw Imprimante laser mono : Pantum BM5100fdw -Imprimante :laser -monochrome multifonction,:format A4-,4-en-1 avec fonctions impression, copie, numérisation et fax, vitesse d'impression de 40ppm, connexion Réseau :LAN RJ45-, Wifichrome multifonction, format A4, 4-en-1 avec fonctions impression, copie, numérisation et fax, vitesse d'impression de 40ppm, connexion Réseau LAN RJ45, Wifi",
    cat: "Imprimante",
    pdf: BM5100,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "IMPRIMANTE PANTUM BP5100DN",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Monochrome Laser PANTUM BP5100DN : Fonctions Impression - :Capacité Bac à papier 250 pages - :Formats papier -: A4 - Technologie d’impression Laser Monochrome - :Vitesse d’impression Noir & Blanc Jusqu’à 40 pages par minute en A4 -: Résolution 1200 dpi -: Mémoire 512 Mo - Connectivité Ethernet, USB 2.0 -:Auto-Duplex-, Network-Ready : Impression silencieuse - faible encombrement et respectueux de l'environnement -: cartouches à haut rendement en option - processeur haute vitesse 1,2 GHz - Dimensions: 364 x 344 x 257 mm - Poids: 9.3 kg - Garantie: 1 an",
    cat: "Imprimante",
    pdf: BP5100DN,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },
  {
    _id: "2005",
    img: IMPRIMANTE_PANTUM_M6609N,
    productName: "IMPRIMANTE PANTUM M6609N",
    color: "Blanc",
    badge: false,
    brand: "Pantum",
    des: "Imprimante Laser 3en1 à toner rechargeable PANTUM M6609N - Capacité d'impression Jusqu'à 1600 pages - Vitesse d’impression : 22 ppm (A4) / 23 ppm (Lettre) - Résolution (impression, copie et numérisation) : 1200×1200dpi - Heure de la première impression : Moins de 7.8s - Connectivité : USB 2.0 haute vitesse - Vitesse de copie : 22cpm (A4) / 23cpm (Lettre) - Capacité du chargeur automatique de documents : 35 pages - Entrée papier : 150 pages - Sortie papier : 100 pages - Dimensions : 417 x 305 x 301 mm - Poids : 8.5 kg - Garantie 1 an",
    cat: "Imprimante",
    pdf: M6609N,
    ficheTech: [
      { label: "Print Speed", value: "22ppm (A4) / 23ppm (Letter)" },
      { label: "Resolution (print, copy & scan)", value: "1200×1200dpi" },
      { label: "First Print Out Time", value: "Less than 7.8s" },
      { label: "Processor", value: "600 MHz" },
      { label: "Memory", value: "128 MB" },
      { label: "Duplex Mode", value: "Manual" },
      {
        label: "Connectivity",
        value: [
          "Hi-speed USB 2.0",
          "Hi-speed USB 2.0 10/100Base-Tx Ethernet",
          "Hi-speed USB 2.0 10/100Base-Tx Ethernet WiFi 802.11b/g/n",
        ],
      },
      { label: "Max. Monthly Volume", value: "20,000 pages" },
      { label: "Recommended Monthly Volume", value: "2000 pages" },
      { label: "Copy Speed", value: "22cpm (A4) / 23cpm (Letter)" },
      { label: "First Copy Out Time", value: "Less than 12 seconds" },
      { label: "Zoom", value: "25% - 400%" },
      { label: "Max. Copy Pages", value: "1 - 99 pages" },
      {
        label: "Additional Function",
        value: "ID copy, Receipt copy, N-up copy, Clone copy",
      },
      { label: "Scanner Type", value: "Flatbed+ADF" },
      {
        label: "Max. Scan Size",
        value: "216 x 297mm (Flatbed), 216 x 356mm (ADF)",
      },
      { label: "Color Scanning", value: "Yes" },
      { label: "Output Function", value: "Scan to E-mail, PC, FTP" },
      { label: "Paper Input Capacity", value: "150 pages" },
      { label: "Paper Output Capacity", value: "100 pages" },
      {
        label: "Media Type",
        value: "Plain, Thick, Transparency, Cardstock, Label, Envelope, Thin",
      },
      {
        label: "Media Size",
        value:
          "A4, A5, A6, JIS B5, ISO B5, B6, Letter, Legal, Executive, Statement, Monarch envelope, DL envelope, C5 envelope, C6 envelope, NO.10 envelope, Japanese Postcard, Folio, Oficio, Big 16k, 32k, 16k, Big 32k, ZL, Yougata4, Postcard, Younaga3, Nagagata3, Yougata2",
      },
      { label: "Media Weight", value: "60~163g/m²" },
      {
        label: "Operating System Compatibility",
        value:
          "Microsoft Windows Server2003/Server2008/Server2012/XP/Vista/Win7/Win8/Win8.1/Win10 (32/64 Bit), Mac OS 10.7-10.13, Linux (Ubuntu 12.04&14.04&16.04&18.04)",
      },
      {
        label: "Dimensions (W×D×H)",
        value: "417x305x301mm(16.4''×12.0''×11.8'')",
      },
      { label: "Weight (with Cartridges)", value: "8.5Kg (18.7lb)" },
      { label: "Humidity Range", value: "20 - 80%" },
      { label: "Energy Efficiency", value: "ENERGY STAR® 2.0 certified" },
      { label: "Starter Toner Cartridge", value: "1600 pages" },
      { label: "Standard Replacement Consumable", value: "PD-219 (1600)" },
    ],
  },

  {
    _id: "20005",
    img: IMPRIMANTE_PANTUM_M6559N,
    productName: "IMPRIMANTE PANTUM M6559N",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser 3en1 à toner rechargeable PANTUM M6559N - Capacité d'impression Jusqu'à 1600 pages - Vitesse d’impression : 22 ppm (A4) / 23 ppm (Lettre) - Résolution (impression, copie et numérisation) : 1200×1200dpi - Heure de la première impression : Moins de 7.8s - Connectivité : USB 2.0 haute vitesse - Vitesse de copie : 22cpm (A4) / 23cpm (Lettre) - Capacité du chargeur automatique de documents : 35 pages - Entrée papier : 150 pages - Sortie papier : 100 pages - Dimensions : 417 x 305 x 301 mm - Poids : 8.5 kg - Garantie 1 an",
    cat: "Imprimante",
    pdf: M6559N,
    ficheTech: [
      { label: "Print Speed", value: "22ppm (A4) / 23ppm (Letter)" },
      { label: "Resolution (print, copy & scan)", value: "1200×1200dpi" },
      { label: "First Print Out Time", value: "Less than 7.8s" },
      { label: "Processor", value: "600 MHz" },
      { label: "Memory", value: "128 MB" },
      { label: "Duplex Mode", value: "Manual" },
      {
        label: "Connectivity",
        value: [
          "Hi-speed USB 2.0",
          "Hi-speed USB 2.0 10/100Base-Tx Ethernet",
          "Hi-speed USB 2.0 10/100Base-Tx Ethernet WiFi 802.11b/g/n",
        ],
      },
      { label: "Max. Monthly Volume", value: "20,000 pages" },
      { label: "Recommended Monthly Volume", value: "2000 pages" },
      { label: "Copy Speed", value: "22cpm (A4) / 23cpm (Letter)" },
      { label: "First Copy Out Time", value: "Less than 12 seconds" },
      { label: "Zoom", value: "25% - 400%" },
      { label: "Max. Copy Pages", value: "1 - 99 pages" },
      {
        label: "Additional Function",
        value: "ID copy, Receipt copy, N-up copy, Clone copy",
      },
      { label: "Scanner Type", value: "Flatbed+ADF" },
      {
        label: "Max. Scan Size",
        value: "216 x 297mm (Flatbed), 216 x 356mm (ADF)",
      },
      { label: "Color Scanning", value: "Yes" },
      { label: "Output Function", value: "Scan to E-mail, PC, FTP" },
      { label: "Paper Input Capacity", value: "150 pages" },
      { label: "Paper Output Capacity", value: "100 pages" },
      {
        label: "Media Type",
        value: "Plain, Thick, Transparency, Cardstock, Label, Envelope, Thin",
      },
      {
        label: "Media Size",
        value:
          "A4, A5, A6, JIS B5, ISO B5, B6, Letter, Legal, Executive, Statement, Monarch envelope, DL envelope, C5 envelope, C6 envelope, NO.10 envelope, Japanese Postcard, Folio, Oficio, Big 16k, 32k, 16k, Big 32k, ZL, Yougata4, Postcard, Younaga3, Nagagata3, Yougata2",
      },
      { label: "Media Weight", value: "60~163g/m²" },
      {
        label: "Operating System Compatibility",
        value:
          "Microsoft Windows Server2003/Server2008/Server2012/XP/Vista/Win7/Win8/Win8.1/Win10 (32/64 Bit), Mac OS 10.7-10.13, Linux (Ubuntu 12.04&14.04&16.04&18.04)",
      },
      {
        label: "Dimensions (W×D×H)",
        value: "417x305x301mm(16.4''×12.0''×11.8'')",
      },
      { label: "Weight (with Cartridges)", value: "8.5Kg (18.7lb)" },
      { label: "Humidity Range", value: "20 - 80%" },
      { label: "Energy Efficiency", value: "ENERGY STAR® 2.0 certified" },
      { label: "Starter Toner Cartridge", value: "1600 pages" },
      { label: "Standard Replacement Consumable", value: "PD-219 (1600)" },
    ],
  },

  {
    _id: "206",
    img: IMPRIMANTE_PANTUM_P3300DN,
    productName: "IMPRIMANTE PANTUM P3300DN",
    color: "Blanc",
    badge: false,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM P3300DN - Fonctions: Impression - Technologie d'impression: Laser - Format Papier: A4-A5 - Vitesse d’impression: 33 ppm (A4) / 35 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Papier Bac d'alimentation: 250 pages - Sortie papier: 150 page - Mémoire: 256 Mo - Impression recto verso: Automatique - Heure de la première impression: Moins de 8.2s  - Taille du support: A4, A5, JIS B5, IS0 B5, A6, Lettre, Légal, Exécutif, Folio, Oficio, Déclaration, Carte postale japonaise, ZL, Big 16K, Big 32K, 16K, 32K, B6， Yougata4, Carte postale, Younaga3, Nagagata3, Yougata2 - Connecteurs: USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx - Dimensions: 354 x 334 x 232mm - Poids: 6,8 kg - Couleur: Blanc",
    cat: "Imprimante",
    pdf: P3300DN,
    ficheTech: [
      { label: "gtin	", value: "P3300DN      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256MO      " },
      { label: "Technologie d impression		", value: "laser      " },
      { label: "Impression		", value: "Noir & Blanc      " },
      { label: "Connectivite		", value: "Réseau      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      {
        label: "Résolution d impression		",
        value: "1 200 x 1 200 dpi (maximum)      ",
      },
      { label: "formats	", value: "A4      " },
      {
        label: "Connecteurs		",
        value: "USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx      ",
      },
      { label: "Fonctionnalités		", value: "Impression      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      { label: "Dimensions		", value: "354 x 334 x 232mm      " },
      { label: "Garantie	", value: "1ANS      " },
    ],
  },

  {
    _id: "207",
    img: IMPRIMANTE_PANTUM_P3300DW,
    productName: "IMPRIMANTE PANTUM P3300DW",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM P3300DW - Fonctions: Impression - Technologie d'impression: Laser - Format Papier: A4-A5 - Vitesse d’impression: 33 ppm (A4) / 35 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Papier Bac d'alimentation: 250 pages - Sortie papier: 150 page - Mémoire: 256 Mo - Impression recto verso: Automatique - Heure de la première impression: Moins de 8.2s - Interface: Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n - Connecteurs: USB ; WIFI - Dimensions: 354 x 334 x 232mm - Poids: 6,8 kg - Couleur: Blanc",
    cat: "Imprimante",
    pdf: P3300DW,
    ficheTech: [
      { label: "gtin		", value: "P3300DW      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256 Mo      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Connectivite	", value: "WIFI      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      { label: "Résolution d impression		", value: "Max.1200x1200 dpi      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      {
        label: "Interface Réseau	",
        value:
          "Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n      ",
      },
      {
        label: "Contenu de L'emballage		",
        value:
          "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
      },
      { label: "Garantie	", value: "1 ANS      " },
    ],
  },

  {
    _id: "208",
    img: IMPRIMANTE_PANTUM_P2509W,
    productName: "IMPRIMANTE PANTUM P2509W",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM P2509W - Fonctions: Impression - Technologie d'impression: Laser - Format Papier: A4 - Vitesse d’impression: 22 ppm (A4) / 23 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Entrée papier: de 150 feuilles - Sortie papier: 100 page - Mémoire: 128 Mo - Impression recto verso: Manuel - Heure de la première impression: Moins de 7.8s - Taille du support: A4, A5, A6, JIS B5, ISO B5, B6, Lettre, Légal, Exécutif, Déclaration, Enveloppe Monarch, Enveloppe DL, enveloppe C5, enveloppe C6, enveloppe NO.10, carte postale japonaise, Folio, Oficio, Grand 16k, 32k, 16k, Grand 32k, ZL,Yougata4, Carte postale, Younaga3, Nagagata3, Yougata2 - Toner rechargeable - Connecteurs: USB 2.0 ; Wi-Fi - Dimensions: 337 x 220 x 178 mm - Poids: 4,75 kg - Couleur: Blanc.",
    cat: "Imprimante",
    pdf: P25009W,
    ficheTech: [
      { label: "Print Speed", value: "22ppm(A4) / 23ppm(Letter)" },
      { label: "First print out time (FPOT)", value: "<7.8s" },
      { label: "Maximum monthly volume", value: "15 000" },
      { label: "Recommended monthly volume", value: "1500 pages" },
      { label: "Resolution(dpi)", value: "1200x1200" },
      { label: "Print languages", value: "GDI" },
      { label: "Duplex Mode", value: "Manual" },
      { label: "Paper input", value: "150" },
      { label: "Paper output", value: "100" },
      {
        label: "Media type",
        value: "Plain, Thick, Transparency, Cardstock, Lable, Envelope, Thin",
      },
      {
        label: "Dimensions (W*D*H)",
        value: "337*220*178mm (13.27*8.66*7.01 inch)",
      },
      { label: "Weight (kg)", value: "4.75kg (10.47lbs)" },
      { label: "Noise", value: "Printing:52dB, Standby:30dB" },
      {
        label: "Power Consumption",
        value: "Printing: Average 370W, Ready: 38W, Sleep Mode: Less than 2W",
      },
      {
        label: "Operating system compatibility",
        value:
          "Microsoft Windows Server2003/Server2008/Server2012/XP/Vista/Win7/Win8/Win8.1/Win10（32/64 Bit），Mac OS 10.7-10.13，Linux（Ubuntu 12.04&14.04&16.04&18.04）",
      },
      { label: "Connectivity", value: "Hi-Speed USB 2.0; WiFi 802.11b/g/n" },
      { label: "Processor speed", value: "600MHz" },
      { label: "Memory", value: "128MB" },
      { label: "Starter Toner cartridge", value: "1600 pages" },
      { label: "Standard replacement Consumable", value: "PD-219 (1600)" },
    ],
  },
  {
    _id: "233",
    img: IMPRIMANTE_PANTUM_P2509,
    productName: "IMPRIMANTE PANTUM P2509",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM P2509 - Fonctions Impression - Capacité d'impression Jusqu'à :1600 pages - Formats papier: A4 - Technologie d’impression Laser Monochrome - Vitesse d’impression Noir & Blanc: Jusqu’à 22 pages par minute en A4 - Résolution: 1200 dpi - Mémoire: 128 Mo - Connectivité: USB 2.0 - Dimensions: 337 x 220 x 178 mm - Poids: 4.75 kg - Toner recheargeable - Garantie: 1 an",
    cat: "Imprimante",
    pdf: P25009,
    ficheTech: [
      { label: "Print Speed", value: "22ppm(A4) / 23ppm(Letter)" },
      { label: "First print out time (FPOT)", value: "<7.8s" },
      { label: "Maximum monthly volume", value: "15 000" },
      { label: "Recommended monthly volume", value: "1500 pages" },
      { label: "Resolution(dpi)", value: "1200x1200" },
      { label: "Print languages", value: "GDI" },
      { label: "Duplex Mode", value: "Manual" },
      { label: "Paper input", value: "150" },
      { label: "Paper output", value: "100" },
      {
        label: "Media type",
        value: "Plain, Thick, Transparency, Cardstock, Lable, Envelope, Thin",
      },
      {
        label: "Dimensions (W*D*H)",
        value: "337*220*178mm (13.27*8.66*7.01 inch)",
      },
      { label: "Weight (kg)", value: "4.75kg (10.47lbs)" },
      { label: "Noise", value: "Printing:52dB, Standby:30dB" },
      {
        label: "Power Consumption",
        value: "Printing: Average 370W, Ready: 38W, Sleep Mode: Less than 2W",
      },
      {
        label: "Operating system compatibility",
        value:
          "Microsoft Windows Server2003/Server2008/Server2012/XP/Vista/Win7/Win8/Win8.1/Win10（32/64 Bit），Mac OS 10.7-10.13，Linux（Ubuntu 12.04&14.04&16.04&18.04）",
      },
      { label: "Connectivity", value: "Hi-Speed USB 2.0; WiFi 802.11b/g/n" },
      { label: "Processor speed", value: "600MHz" },
      { label: "Memory", value: "128MB" },
      { label: "Starter Toner cartridge", value: "1600 pages" },
      { label: "Standard replacement Consumable", value: "PD-219 (1600)" },
    ],
  },
];
